# TCL File Generated by Component Editor 18.1
# Sat Aug 14 17:00:07 PDT 2021
# DO NOT MODIFY


# 
# avalon_to_fpro_bridge "Avalon-MM to FPRO Bridge" v1.1
# aw 2021.08.14.17:00:07
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module avalon_to_fpro_bridge
# 
set_module_property DESCRIPTION ""
set_module_property NAME avalon_to_fpro_bridge
set_module_property VERSION 1.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR aw
set_module_property DISPLAY_NAME "Avalon-MM to FPRO Bridge"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avalon_to_fpro_bridge
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avalon_to_fpro_bridge.sv SYSTEM_VERILOG PATH avalon_to_fpro_bridge.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter BRG_BASE STD_LOGIC_VECTOR 3221225472 ""
set_parameter_property BRG_BASE DEFAULT_VALUE 3221225472
set_parameter_property BRG_BASE DISPLAY_NAME BRG_BASE
set_parameter_property BRG_BASE WIDTH 32
set_parameter_property BRG_BASE TYPE STD_LOGIC_VECTOR
set_parameter_property BRG_BASE UNITS None
set_parameter_property BRG_BASE DESCRIPTION ""
set_parameter_property BRG_BASE HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point clock_out
# 
add_interface clock_out clock start
set_interface_property clock_out associatedDirectClock clock
set_interface_property clock_out clockRate 0
set_interface_property clock_out clockRateKnown false
set_interface_property clock_out ENABLED true
set_interface_property clock_out EXPORT_OF ""
set_interface_property clock_out PORT_NAME_MAP ""
set_interface_property clock_out CMSIS_SVD_VARIABLES ""
set_interface_property clock_out SVD_ADDRESS_GROUP ""

add_interface_port clock_out clk_out clk Output 1


# 
# connection point reset_source
# 
add_interface reset_source reset start
set_interface_property reset_source associatedClock clock
set_interface_property reset_source associatedDirectReset ""
set_interface_property reset_source associatedResetSinks reset
set_interface_property reset_source synchronousEdges DEASSERT
set_interface_property reset_source ENABLED true
set_interface_property reset_source EXPORT_OF ""
set_interface_property reset_source PORT_NAME_MAP ""
set_interface_property reset_source CMSIS_SVD_VARIABLES ""
set_interface_property reset_source SVD_ADDRESS_GROUP ""

add_interface_port reset_source reset_out reset Output 1


# 
# connection point avalon_MM_interface
# 
add_interface avalon_MM_interface avalon end
set_interface_property avalon_MM_interface addressUnits WORDS
set_interface_property avalon_MM_interface associatedClock clock
set_interface_property avalon_MM_interface associatedReset reset
set_interface_property avalon_MM_interface bitsPerSymbol 8
set_interface_property avalon_MM_interface burstOnBurstBoundariesOnly false
set_interface_property avalon_MM_interface burstcountUnits WORDS
set_interface_property avalon_MM_interface explicitAddressSpan 1073741824
set_interface_property avalon_MM_interface holdTime 0
set_interface_property avalon_MM_interface linewrapBursts false
set_interface_property avalon_MM_interface maximumPendingReadTransactions 0
set_interface_property avalon_MM_interface maximumPendingWriteTransactions 0
set_interface_property avalon_MM_interface readLatency 1
set_interface_property avalon_MM_interface readWaitStates 0
set_interface_property avalon_MM_interface readWaitTime 0
set_interface_property avalon_MM_interface setupTime 0
set_interface_property avalon_MM_interface timingUnits Cycles
set_interface_property avalon_MM_interface writeWaitTime 0
set_interface_property avalon_MM_interface ENABLED true
set_interface_property avalon_MM_interface EXPORT_OF ""
set_interface_property avalon_MM_interface PORT_NAME_MAP ""
set_interface_property avalon_MM_interface CMSIS_SVD_VARIABLES ""
set_interface_property avalon_MM_interface SVD_ADDRESS_GROUP ""

add_interface_port avalon_MM_interface read read Input 1
add_interface_port avalon_MM_interface write write Input 1
add_interface_port avalon_MM_interface chipselect chipselect Input 1
add_interface_port avalon_MM_interface byteenable byteenable Input 4
add_interface_port avalon_MM_interface address address Input 30
add_interface_port avalon_MM_interface writedata writedata Input 32
add_interface_port avalon_MM_interface readdata readdata Output 32
set_interface_assignment avalon_MM_interface embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_MM_interface embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_MM_interface embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_MM_interface embeddedsw.configuration.isPrintableDevice 0


# 
# connection point fp_rd_data
# 
add_interface fp_rd_data conduit end
set_interface_property fp_rd_data associatedClock clock
set_interface_property fp_rd_data associatedReset ""
set_interface_property fp_rd_data ENABLED true
set_interface_property fp_rd_data EXPORT_OF ""
set_interface_property fp_rd_data PORT_NAME_MAP ""
set_interface_property fp_rd_data CMSIS_SVD_VARIABLES ""
set_interface_property fp_rd_data SVD_ADDRESS_GROUP ""

add_interface_port fp_rd_data fp_rd_data conduit Input 32


# 
# connection point fp_wr_data
# 
add_interface fp_wr_data conduit end
set_interface_property fp_wr_data associatedClock clock
set_interface_property fp_wr_data associatedReset ""
set_interface_property fp_wr_data ENABLED true
set_interface_property fp_wr_data EXPORT_OF ""
set_interface_property fp_wr_data PORT_NAME_MAP ""
set_interface_property fp_wr_data CMSIS_SVD_VARIABLES ""
set_interface_property fp_wr_data SVD_ADDRESS_GROUP ""

add_interface_port fp_wr_data fp_wr_data conduit Output 32


# 
# connection point fp_addr
# 
add_interface fp_addr conduit end
set_interface_property fp_addr associatedClock clock
set_interface_property fp_addr associatedReset ""
set_interface_property fp_addr ENABLED true
set_interface_property fp_addr EXPORT_OF ""
set_interface_property fp_addr PORT_NAME_MAP ""
set_interface_property fp_addr CMSIS_SVD_VARIABLES ""
set_interface_property fp_addr SVD_ADDRESS_GROUP ""

add_interface_port fp_addr fp_addr conduit Output 21


# 
# connection point fp_wr
# 
add_interface fp_wr conduit end
set_interface_property fp_wr associatedClock clock
set_interface_property fp_wr associatedReset ""
set_interface_property fp_wr ENABLED true
set_interface_property fp_wr EXPORT_OF ""
set_interface_property fp_wr PORT_NAME_MAP ""
set_interface_property fp_wr CMSIS_SVD_VARIABLES ""
set_interface_property fp_wr SVD_ADDRESS_GROUP ""

add_interface_port fp_wr fp_wr conduit Output 1


# 
# connection point fp_rd
# 
add_interface fp_rd conduit end
set_interface_property fp_rd associatedClock clock
set_interface_property fp_rd associatedReset ""
set_interface_property fp_rd ENABLED true
set_interface_property fp_rd EXPORT_OF ""
set_interface_property fp_rd PORT_NAME_MAP ""
set_interface_property fp_rd CMSIS_SVD_VARIABLES ""
set_interface_property fp_rd SVD_ADDRESS_GROUP ""

add_interface_port fp_rd fp_rd conduit Output 1


# 
# connection point fp_mmio_cs
# 
add_interface fp_mmio_cs conduit end
set_interface_property fp_mmio_cs associatedClock clock
set_interface_property fp_mmio_cs associatedReset ""
set_interface_property fp_mmio_cs ENABLED true
set_interface_property fp_mmio_cs EXPORT_OF ""
set_interface_property fp_mmio_cs PORT_NAME_MAP ""
set_interface_property fp_mmio_cs CMSIS_SVD_VARIABLES ""
set_interface_property fp_mmio_cs SVD_ADDRESS_GROUP ""

add_interface_port fp_mmio_cs fp_mmio_cs conduit Output 1


# 
# connection point fp_video_cs
# 
add_interface fp_video_cs conduit end
set_interface_property fp_video_cs associatedClock clock
set_interface_property fp_video_cs associatedReset ""
set_interface_property fp_video_cs ENABLED true
set_interface_property fp_video_cs EXPORT_OF ""
set_interface_property fp_video_cs PORT_NAME_MAP ""
set_interface_property fp_video_cs CMSIS_SVD_VARIABLES ""
set_interface_property fp_video_cs SVD_ADDRESS_GROUP ""

add_interface_port fp_video_cs fp_video_cs conduit Output 1

